import './components/map'
import './components/slider'
// import './components/range-slider'
import 'simplebar/dist/simplebar.css'
import './components/aside'
import './components/catalog'
import './components/dropdown'
import './components/header'
import './components/media'
import './components/modal'
import './components/player'
import './components/product'
import './components/reviews-page.js'
import './components/reviews.js'
import './components/selects'
import './components/smooth-scroll'
import './components/tabs-media'
import './components/tabs-services'



